<a href="https://colab.research.google.com/github/ArquimedesG/Machine_Learning_Colabs/blob/main/ML_S10_Decision_Trees_08AU23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Titanic Dataset

 This dataset is a widely used dataset that contains information on the passengers who were aboard the Titanic when it sank on its maiden voyage in 1912.

 The dataset includes features such as age, sex, passenger class, and fare paid, as well as whether or not the passenger survived the sinking.

 The dataset is often used for machine learning and data analysis tasks, such as predicting survival based on passenger characteristics or exploring patterns in the data.

 The Titanic dataset is a classic example of data analysis and is a great starting point for those new to data science.

The Titanic dataset is available in CSV format and contains two files, one for training and one for testing.

The training file is used to build the machine learning model, while the testing file is used to test the performance of the model.

Data Dictionary:

    Attributes	      Definition	                          Key
    sex	              Sex/Gender	                        male/female
    age	              Age
    sibsp	            siblings of the passenger	              0/1 /2 …
    parch	            parents / children aboard the Titanic	  0/1/2 …
    fare	            Passenger fare
    embarked	        Port of Embarkation	                    C : Cherbourg, Q : Queenstown, S : Southampton
    class	            Ticket class	                          First / Second / Third
    who	              categories to passengers	              male, female, child
    alone	            he was alone in ship or no	            0/1
    survived		                                              0/1

###  Decision Trees

Decision Trees (DTs) are a non-parametric supervised learning method used for classification and regression.

The goal is to create a model that predicts the value of a target variable by learning simple decision rules inferred from the data features.

A tree can be seen as a piecewise constant approximation.

For instance, in the example below, decision trees learn from data to approximate a sine curve with a set of if-then-else decision rules.

The deeper the tree, the more complex the decision rules and the fitter the model.



Some advantages of decision trees are:

    Simple to understand and to interpret.
    Trees can be visualized.

    Requires little data preparation.
    Other techniques often require data normalization, dummy variables need to be created and blank values to be removed.
    Note however that this module does not support missing values.

    The cost of using the tree (i.e., predicting data) is logarithmic in the number of data points used to train the tree.

    Able to handle both numerical and categorical data.
    However, the scikit-learn implementation does not support categorical variables for now.
    Other techniques are usually specialized in analyzing datasets that have only one type of variable.

    Able to handle multi-output problems.

    Uses a white box model.
    If a given situation is observable in a model, the explanation for the condition is easily explained by boolean logic.
    By contrast, in a black box model (e.g., in an artificial neural network), results may be more difficult to interpret.

    Possible to validate a model using statistical tests.
    That makes it possible to account for the reliability of the model.

    Performs well even if its assumptions are somewhat violated by the true model from which the data were generated.

The disadvantages of decision trees include:

    Decision-tree learners can create over-complex trees that do not generalize the data well.
    This is called overfitting.
    Mechanisms such as pruning, setting the minimum number of samples required at a leaf node or setting the maximum depth of the tree are necessary to avoid this problem.

    Decision trees can be unstable because small variations in the data might result in a completely different tree being generated.
    This problem is mitigated by using decision trees within an ensemble.

    Predictions of decision trees are neither smooth nor continuous, but piecewise constant approximations as seen in the above figure.
    Therefore, they are not good at extrapolation.

    The problem of learning an optimal decision tree is known to be NP-complete under several aspects of optimality and even for simple concepts.
    Consequently, practical decision-tree learning algorithms are based on heuristic algorithms such as the greedy algorithm where locally optimal decisions are made at each node.
    Such algorithms cannot guarantee to return the globally optimal decision tree.
    This can be mitigated by training multiple trees in an ensemble learner, where the features and samples are randomly sampled with replacement.

There are concepts that are hard to learn because decision trees do not express them easily, such as XOR, parity or multiplexer problems.

Decision tree learners create biased trees if some classes dominate.

It is therefore recommended to balance the dataset prior to fitting with the decision tree.

### sklearn.tree.DecisionTreeClassifier

**class sklearn.tree.DecisionTreeClassifier(*, criterion='gini', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0)**

**Parameters:**

    criterion : {“gini”, “entropy”, “log_loss”}, default=”gini”
    The function to measure the quality of a split.
    Supported criteria are “gini” for the Gini impurity and “log_loss” and “entropy” both for the Shannon information gain.

    splitter : {“best”, “random”}, default=”best”
    The strategy used to choose the split at each node.
    Supported strategies are “best” to choose the best split and “random” to choose the best random split.

    max_depth : int, default=None
    The maximum depth of the tree.
    If None, then nodes are expanded until all leaves are pure or until all leaves contain less than min_samples_split samples.

    min_samples_split : int or float, default=2
    The minimum number of samples required to split an internal node:

      If int, then consider min_samples_split as the minimum number.

      If float, then min_samples_split is a fraction and ceil(min_samples_split * n_samples) are the minimum number of samples for each split.

    min_samples_leaf : int or float, default=1
    The minimum number of samples required to be at a leaf node.
    A split point at any depth will only be considered if it leaves at least min_samples_leaf training samples in each of the left and right branches.
    This may have the effect of smoothing the model, especially in regression.

      If int, then consider min_samples_leaf as the minimum number.

      If float, then min_samples_leaf is a fraction and ceil(min_samples_leaf * n_samples) are the minimum number of samples for each node.

    min_weight_fraction_leaf : float, default=0.0
    The minimum weighted fraction of the sum total of weights (of all the input samples) required to be at a leaf node.
    Samples have equal weight when sample_weight is not provided.

    max_features : int, float or {“auto”, “sqrt”, “log2”}, default=None
    The number of features to consider when looking for the best split:

      If int, then consider max_features features at each split.

      If float, then max_features is a fraction and max(1, int(max_features * n_features_in_)) features are considered at each split.

      If “sqrt”, then max_features=sqrt(n_features).

      If “log2”, then max_features=log2(n_features).

      If None, then max_features=n_features.

      Note: the search for a split does not stop until at least one valid partition of the node samples is found, even if it requires to effectively inspect more than max_features features.

    random_state : int, RandomState instance or None, default=None
    Controls the randomness of the estimator.
    The features are always randomly permuted at each split, even if splitter is set to "best".
    When max_features < n_features, the algorithm will select max_features at random at each split before finding the best split among them.
    But the best found split may vary across different runs, even if max_features=n_features.
    That is the case, if the improvement of the criterion is identical for several splits and one split has to be selected at random.
    To obtain a deterministic behaviour during fitting, random_state has to be fixed to an integer.

    max_leaf_nodes : int, default=None
    Grow a tree with max_leaf_nodes in best-first fashion.
    Best nodes are defined as relative reduction in impurity.
    If None then unlimited number of leaf nodes.

    min_impurity_decrease : float, default=0.0
    A node will be split if this split induces a decrease of the impurity greater than or equal to this value.

    The weighted impurity decrease equation is the following:

      N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)

    where N is the total number of samples,
    N_t is the number of samples at the current node,
    N_t_L is the number of samples in the left child, and
    N_t_R is the number of samples in the right child.

    N, N_t, N_t_R and N_t_L all refer to the weighted sum, if sample_weight is passed.

    class_weight : dict, list of dict or “balanced”, default=None
    Weights associated with classes in the form {class_label: weight}.
    If None, all classes are supposed to have weight one.
    For multi-output problems, a list of dicts can be provided in the same order as the columns of y.

    Note that for multioutput (including multilabel) weights should be defined for each class of every column in its own dict.
    For example, for four-class multilabel classification weights should be [{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of [{1:1}, {2:5}, {3:1}, {4:1}].

    The “balanced” mode uses the values of y to automatically adjust weights inversely proportional to class frequencies in the input data as n_samples / (n_classes * np.bincount(y))

    For multi-output, the weights of each column of y will be multiplied.

    Note that these weights will be multiplied with sample_weight (passed through the fit method) if sample_weight is specified.

    ccp_alphanon-negative :   float, default=0.0
    Complexity parameter used for Minimal Cost-Complexity Pruning.
    The subtree with the largest cost complexity that is smaller than ccp_alpha will be chosen.
    By default, no pruning is performed. See Minimal Cost-Complexity Pruning for details.

**Attributes:**

    classes_ : ndarray of shape (n_classes,) or list of ndarray
    The classes labels (single output problem), or a list of arrays of class labels (multi-output problem).

    feature_importances_ : ndarray of shape (n_features,)
    Return the feature importances.

    max_features_ : int
    The inferred value of max_features.

    n_classes_ : int or list of int
    The number of classes (for single output problems), or a list containing the number of classes for each output (for multi-output problems).

    n_features_in_ : int
    Number of features seen during fit.

    feature_names_in_ : ndarray of shape (n_features_in_,)
    Names of features seen during fit.
    Defined only when X has feature names that are all strings.

    n_outputs_ : int
    The number of outputs when fit is performed.

    tree_ : Tree instance
    The underlying Tree object.

In [ ]:
#  Importing Numpy
import numpy as np

#  Importing Matplotlib.pyplot
import matplotlib.pyplot as plt

#  Importing Pandas
import pandas as pd

#  Importing train_test_split from sklearn.modelselection
from sklearn.model_selection import train_test_split

#  Importing tree from sklearn
from sklearn import tree

In [ ]:
#  Reading the dataset from a CSV file and storing as dataframe df
df = pd.read_csv("https://gist.githubusercontent.com/javierIA/403a1027bd6894f865a508652c338d20/raw/fd09d4255ce0ef4ab01eb6a5144c6c887f72045c/datos")

#  Displaying the dataframe
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
706,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
707,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
708,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
709,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
710,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
#  Creating a new columnd "Sex_male" based on "Sex" column but changing values (from: male/female to 1/0) and dropping original "Sex" column
df=pd.get_dummies(df, columns=["Sex"], drop_first=True)
#  Displaying new dataframe
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,0
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
706,886,0,3,"Rice, Mrs. William (Margaret Norton)",39.0,0,5,382652,29.1250,NaN,Q,0
707,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S,1
708,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,0
709,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C,1
710,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q,1

In [ ]:
#  Selecting columns "Sex_male", "Fare", "Age", "Pclass", "SibSp" and "Survived" to create the dataframe data to work with
data=df[["Sex_male","Fare", "Age", "Pclass","SibSp","Survived"]]

#  Displaying new dataframe
data

     Sex_male     Fare   Age  Pclass  SibSp  Survived
0           1   7.2500  22.0       3      1         0
1           0  71.2833  38.0       1      1         1
2           0   7.9250  26.0       3      0         1
3           0  53.1000  35.0       1      1         1
4           1   8.0500  35.0       3      0         0
..        ...      ...   ...     ...    ...       ...
706         0  29.1250  39.0       3      0         0
707         1  13.0000  27.0       2      0         0
708         0  30.0000  19.0       1      0         1
709         1  30.0000  26.0       1      0         1
710         1   7.7500  32.0       3      0         0

[711 rows x 6 columns]

In [ ]:
#  Showing general info for dataframe data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 711 entries, 0 to 710
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Sex_male  711 non-null    uint8
 1   Fare      711 non-null    float64
 2   Age       711 non-null    float64
 3   Pclass    711 non-null    int64
 4   SibSp     711 non-null    int64
 5   Survived  711 non-null    int64
dtypes: float64(2), int64(3), uint8(1)
memory usage: 28.6 KB

In [ ]:
#  Creating the input dataframe X by dropping the column "Survived"
X=data.drop(["Survived"], axis=1)
X

     Sex_male     Fare   Age  Pclass  SibSp
0           1   7.2500  22.0       3      1
1           0  71.2833  38.0       1      1
2           0   7.9250  26.0       3      0
3           0  53.1000  35.0       1      1
4           1   8.0500  35.0       3      0
..        ...      ...   ...     ...    ...
706         0  29.1250  39.0       3      0
707         1  13.0000  27.0       2      0
708         0  30.0000  19.0       1      0
709         1  30.0000  26.0       1      0
710         1   7.7500  32.0       3      0

[711 rows x 5 columns]

In [ ]:
#  Creating the output dataframe Y by copying the column "Survived"
Y=data.Survived

#  Displaying Dataframe content
Y

0      0
1      1
2      1
3      1
4      0
      ..
706    0
707    0
708    1
709    1
710    0
Name: Survived, Length: 711, dtype: int64

In [ ]:
#  Splitting the datasets X, Y into train and test datasets
X_train,  X_test, Y_train, Y_Test= train_test_split(X, Y)

#  Displaying train input dataset
X_train

     Sex_male     Fare   Age  Pclass  SibSp
628         1  26.0000  16.0       2      0
237         1   7.8958  24.0       3      0
543         1   7.7958  18.0       3      0
387         1  29.7000  58.0       1      0
659         1  37.0042   1.0       2      0
..        ...      ...   ...     ...    ...
474         1  26.5500  35.0       1      0
32          0  21.0000  27.0       2      1
376         0  13.7917  23.0       2      0
456         1   7.9250  32.0       3      0
321         1   7.9250  39.0       3      0

[533 rows x 5 columns]

In [ ]:
#  Displaying train output dataset
Y_train

628    0
237    0
543    0
387    0
659    1
      ..
474    1
32     0
376    1
456    1
321    1
Name: Survived, Length: 533, dtype: int64

In [ ]:
#  Defining a classifier clt of type tree
clt=tree.DecisionTreeClassifier(max_leaf_nodes=10)

In [ ]:
#  Fitting the classifier clt with the train data (X_train, Y_train)
clt.fit(X_train, Y_train)

DecisionTreeClassifier(max_leaf_nodes=10)

In [ ]:
#  Importing graphviz to visualize the decision tree
import graphviz

#  Defining the decision tree format
dot_data=tree.export_graphviz(clt, out_file=None,
                              feature_names=X_train.columns.values,
                              class_names=["Not Survived", "Survived"],
                              filled=True,
                              rounded=True,
                              leaves_parallel=False)

In [ ]:
#  Graphing the decision tree
graph=graphviz.Source(dot_data)
graph